"""
GST-compliant invoice PDF generator using ReportLab.
reportlab is already in requirements.txt.
"""
from datetime import datetime
from typing import Optional
import io
import structlog

log = structlog.get_logger(__name__)


async def generate_gst_invoice(
    invoice_number: str, seller_name: str, seller_gstin: str,
    buyer_name: str, buyer_gstin: str, line_items: list,
    subtotal: float, gst_amount: float, total: float,
) -> Optional[str]:
    try:
        pdf_bytes = _build_pdf(invoice_number, seller_name, seller_gstin,
                               buyer_name, buyer_gstin, line_items, subtotal, gst_amount, total)
        return await _save_pdf(pdf_bytes, invoice_number)
    except ImportError:
        log.error("invoice.reportlab_missing", hint="pip install reportlab")
        return None
    except Exception as e:
        log.error("invoice.generation_failed", error=str(e))
        return None


def _build_pdf(invoice_number, seller_name, seller_gstin, buyer_name, buyer_gstin,
               line_items, subtotal, gst_amount, total) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm, topMargin=15*mm, bottomMargin=15*mm)
    styles = getSampleStyleSheet()
    BRAND = colors.HexColor("#FF6B00")
    DARK  = colors.HexColor("#0A0C1A")
    LIGHT = colors.HexColor("#F8F8F8")

    title_s  = ParagraphStyle("t",  fontSize=16, fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=4)
    normal_s = ParagraphStyle("n",  fontSize=9,  fontName="Helvetica",      spaceAfter=2)
    small_s  = ParagraphStyle("s",  fontSize=8,  fontName="Helvetica",      textColor=colors.grey)

    story = []
    story.append(Paragraph("TAX INVOICE", title_s))
    story.append(HRFlowable(width="100%", thickness=2, color=BRAND, spaceAfter=8))

    seller_p = Paragraph(f"<b>{seller_name}</b><br/>GSTIN: {seller_gstin or 'Not registered'}<br/>"
                         f"<font color='grey'>Invoice: {invoice_number} | Date: {datetime.now().strftime('%d %b %Y')}</font>", normal_s)
    buyer_p  = Paragraph(f"<b>Bill To:</b><br/>{buyer_name}<br/>GSTIN: {buyer_gstin or 'N/A'}", normal_s)
    htable   = Table([[seller_p, buyer_p]], colWidths=["50%","50%"])
    htable.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),0)]))
    story.extend([htable, Spacer(1,10)])

    data = [["#","Description","Qty","Rate (₹)","GST %","Amount (₹)"]]
    for i, item in enumerate(line_items, 1):
        qty=item.get("qty",1); rate=float(item.get("rate",0)); gst_r=item.get("gst_rate",18)
        data.append([str(i), item.get("description","Service"), str(qty), f"{rate:,.2f}", f"{gst_r}%", f"{qty*rate:,.2f}"])
    n = len(line_items)
    data += [["","","","","Subtotal",f"₹{subtotal:,.2f}"],
             ["","","","","GST",     f"₹{gst_amount:,.2f}"],
             ["","","","","TOTAL",   f"₹{total:,.2f}"]]

    t = Table(data, colWidths=[8*mm,75*mm,15*mm,28*mm,18*mm,28*mm], repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),DARK), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),8),
        ("ROWBACKGROUNDS",(0,1),(-1,n),[colors.white,LIGHT]),
        ("GRID",(0,0),(-1,n),0.5,colors.HexColor("#DDDDDD")),
        ("FONTNAME",(0,-1),(-1,-1),"Helvetica-Bold"), ("FONTSIZE",(0,-1),(-1,-1),10),
        ("TEXTCOLOR",(0,-1),(-1,-1),BRAND),
        ("LINEABOVE",(0,-3),(-1,-3),1,colors.HexColor("#DDDDDD")),
        ("LINEABOVE",(0,-1),(-1,-1),1.5,BRAND),
        ("ALIGN",(-2,-3),(-1,-1),"RIGHT"), ("ALIGN",(2,1),(5,n),"RIGHT"),
        ("LEFTPADDING",(0,0),(-1,-1),4), ("RIGHTPADDING",(0,0),(-1,-1),4),
        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),
    ]))
    story.extend([t, Spacer(1,12)])
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#DDDDDD")))
    story.append(Spacer(1,6))
    story.append(Paragraph("Computer-generated invoice. No signature required.", small_s))
    story.append(Paragraph("Generated by <b>Vaani</b> — vaani.app", small_s))
    doc.build(story)
    return buffer.getvalue()


async def _save_pdf(pdf_bytes: bytes, invoice_number: str) -> str:
    from app.config import settings
    if settings.AWS_ACCESS_KEY_ID and settings.S3_BUCKET:
        import boto3
        s3 = boto3.client("s3", aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
                          aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
                          region_name=settings.AWS_REGION)
        key = f"invoices/{invoice_number}.pdf"
        s3.put_object(Bucket=settings.S3_BUCKET, Key=key, Body=pdf_bytes,
                      ContentType="application/pdf",
                      ContentDisposition=f'attachment; filename="{invoice_number}.pdf"')
        return f"https://{settings.S3_BUCKET}.s3.{settings.AWS_REGION}.amazonaws.com/{key}"
    else:
        path = f"/tmp/invoice_{invoice_number}.pdf"
        with open(path, "wb") as f:
            f.write(pdf_bytes)
        return path
